name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

# https://github.com/r-lib/actions/tree/v2-branch/setup-pandoc pandoc setup found here
# https://coderefinery.github.io/documentation/gh_workflow/ documentation of doc setup here

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          pip install -e '.[doc,devtools]'
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
